Load library
```{r}
source("../General/general_functions.R")
library(cowplot)
library(eulerr)
library(tidyverse)
```

Load data
```{r}
otu <- readRDS("../Data/rare_votu75_tmean.RDS")
#Remove singletons
otu <- otu[rowSums(otu>0) > 1,]

map <- readRDS("../Data/wetup_map.RDS")

annotation <- readRDS("../Data/vibrant_annotation.RDS") %>% filter(OTU_ID %in% row.names(otu))

vibrant.quality <- readRDS("../Data/vibrant_quality.RDS")
```

Identify integrases, excisionases, and integrated prophages in VIBRANT annotation
```{r}
annotation <- annotation %>% 
  mutate(Integrase = str_detect(Name, "[I|i]ntegrase"),
         Excisionase = str_detect(Name, "[E|e]xcisionase"),
         Prophage = str_detect(OTU_ID, "fragment")) %>% 
  mutate(Temperate = Integrase | Excisionase | Prophage)

#Get vOTUs with at least one of these three attributes
lysogen.df <- annotation %>% 
  filter(Temperate) %>% 
  group_by(OTU_ID) %>% 
  count() %>% 
  ungroup() %>% 
  select(-n) %>% 
  mutate(PredictedLysogen = TRUE) 


lysogen.df

integrase.id <- filter(annotation, Integrase)$OTU_ID %>% unique()
excisionase.id <- filter(annotation, Excisionase)$OTU_ID %>% unique()
prophage.id <- filter(annotation, Prophage)$OTU_ID %>% unique()

temperate.pal <- RColorBrewer::brewer.pal(3, "Set2")

a <- plot(euler(list("Integrase" = integrase.id, "Excisionase" = excisionase.id, "Prophage" = prophage.id)),
     fills = "white",
     edges = list(col = temperate.pal, lex = 5),
     labels = list(fontfamily = "Helvetica",
                   col = temperate.pal,
                   cex = 1), 
     quantities = list(fontfamily = "Helvetica",
                    col = c("black", "black", "black"),
                   cex = 1))

a
```


Generate a data frame with the aggreaged abundances of phages predicted to be temperate
```{r}
lysogen.ab <- otu %>% 
  rel_ab() %>% 
  tidy_otu() %>% 
  mutate(Count = Count/100) %>% 
  left_join(lysogen.df, by = "OTU_ID") %>% 
  mutate(PredictedLysogen = ifelse(is.na(PredictedLysogen), FALSE, TRUE)) %>% 
  group_by(SampleID, PredictedLysogen) %>% 
  summarise(TotalAb = sum(Count),
            Total = sum(Count > 0)) %>% 
  group_by(SampleID) %>% 
  mutate(Fraction = Total/sum(Total)) %>% 
  mutate(Percentage = Fraction * 100) %>% 
  ungroup() %>% 
  inner_join(map, by = "SampleID") %>% 
  filter(Profile == "ViromeD") %>% 
  filter(Status == "Wet" | TimeFctr == "T0") 
```

Plot
```{r}
#Abundances
b <- lysogen.ab %>% 
  ggplot(aes(Time, TotalAb, color = PredictedLysogen)) +
  geom_point(alpha = 0.8) +
  geom_line(data = . %>% group_by(Soil2, Profile2, Time, PredictedLysogen) %>% summarise(Mean = mean(TotalAb)), aes(y = Mean)) +
  ylab("Relative abundance") +
  xlab("Time point (hrs. after wetup)") +
  scale_color_manual(name = "Predicted\ntemperate\nphage", values = c("gray75", "gray25")) +
  facet_grid(Profile2 ~ Soil2) +
  ylim(0,1) +
  theme_bw() +
  theme(text = element_text(size = 12),
        axis.text.x = element_text(angle = 45, hjust = 1))

#Fraction of detected vOTUs
c <- lysogen.ab %>% 
  ggplot(aes(Time, Percentage, color = PredictedLysogen)) +
  geom_point(alpha = 0.8) +
  geom_line(data = . %>% group_by(Soil2, Profile2, Time, PredictedLysogen) %>% summarise(Mean = mean(Percentage)), aes(y = Mean)) +
  ylab("% detected vOTUs") +
  xlab("Time point (hrs. after wetup)") +
  scale_color_manual(name = "Predicted\ntemperate\nphage", values = c("gray75", "gray25")) +
  facet_grid(Profile2 ~ Soil2) +
  ylim(0,100) +
  theme_bw() +
  theme(text = element_text(size = 12),
        axis.text.x = element_text(angle = 45, hjust = 1))

left <- plot_grid(b + theme(legend.position = "none"),
                  c + theme(legend.position = "none"),
                  ncol = 1,
                  align = "hv", axis = "lrbt",
                  labels = c("b", "c"), label_size = 15)

#725:465
bottom <- plot_grid(left, get_legend(b), rel_widths = c(5,1))

plot_grid(a, bottom, ncol = 1, rel_heights = c(1,2.5), labels = c("a", NA), label_size = 15)
```
stats
```{r}
lysogen.ab %>% 
  group_by(PredictedLysogen) %>% 
  summarise(MeanPercentage = mean(Percentage),
            MeanRelAb = mean(TotalAb),
            MinPercentage = min(Percentage),
            MinRelAb = min(TotalAb),
            MaxPercentage = max(Percentage),
            MaxRelAb = max(TotalAb))

table(row.names(otu) %in% lysogen.df$OTU_ID) / nrow(otu)
```

```{r}
saveRDS(lysogen.df, "../Data/predicted_temperate.RDS")
```

